[package]
name = "sketchbook"
version = "0.1.0"
edition = "2021"

[dependencies]
# Graphics
macroquad = "0.3.16"

# Math
manyvecs = { version = "~0.3", default-features = false, features = ["macroed"] }
